# OneCompiler LLVM子模块配置
# LLVM/MLIR 专用配置

# 子模块根路径
set(ONECOMPILER_SUBMODULE_ROOT "${CMAKE_SOURCE_DIR}/third_party")

# LLVM配置 - 包含MLIR
set(LLVM_SOURCE_DIR "${ONECOMPILER_SUBMODULE_ROOT}/llvm-project/llvm")
set(LLVM_BUILD_DIR "${CMAKE_BINARY_DIR}/third_party/llvm-project")

# LLVM构建参数 - MLIR通过LLVM_ENABLE_PROJECTS=mlir启用
set(LLVM_CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DLLVM_ENABLE_PROJECTS=mlir
    -DLLVM_TARGETS_TO_BUILD=X86
    -DLLVM_ENABLE_EH=ON
    -DLLVM_ENABLE_RTTI=ON
    -DLLVM_ENABLE_ASSERTIONS=ON
    -DLLVM_BUILD_EXAMPLES=OFF
    -DLLVM_BUILD_TESTS=OFF
    -DLLVM_INCLUDE_TESTS=OFF
    -DMLIR_ENABLE_BINDINGS_PYTHON=OFF
)